# Generated by Django 2.0.3 on 2018-04-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('place', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('closing', models.DateTimeField()),
                ('int_capacity', models.IntegerField()),
                ('ext_capacity', models.IntegerField()),
                ('int_price', models.IntegerField()),
                ('ext_price', models.IntegerField()),
                ('display', models.BooleanField()),
                ('status', models.CharField(choices=[('4', 'FINISHED'), ('3', 'PENDING'), ('2', 'VALIDATED'), ('1', 'WAITING')], max_length=1)),
                ('token', models.CharField(max_length=20)),
                ('orga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'OFFICE'), ('3', 'PRESIDENT'), ('2', 'SIMPLE')], max_length=1)),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Association')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
