# Generated by Django 2.0.3 on 2018-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('1', 'OFFICE'), ('3', 'PRESIDENT'), ('2', 'SIMPLE')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
