# Generated by Django 2.0.4 on 2018-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
