# Generated by Django 2.0.4 on 2018-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180424_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(4, 'FINISHED'), (3, 'PENDING'), (5, 'REJECTED'), (2, 'VALIDATED'), (1, 'WAITING')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(1, 'OFFICE'), (3, 'PRESIDENT'), (2, 'SIMPLE')]),
        ),
    ]
