# Generated by Django 2.0.4 on 2018-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180514_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
