# Generated by Django 2.0.4 on 2018-05-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participant_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respo', models.BooleanField()),
                ('pres', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Event')),
            ],
        ),
    ]
