# Generated by Django 2.0.4 on 2018-05-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='pres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='respo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='orga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Association'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='asso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Association'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
