# Generated by Django 2.0.4 on 2018-06-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180524_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
