# Generated by Django 2.0.4 on 2018-06-12 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20180611_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'user')},
        ),
    ]
