# Generated by Django 2.0.4 on 2018-06-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180612_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='asso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Association'),
        ),
    ]
