# Generated by Django 2.0.4 on 2018-06-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_staff_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='asso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Association'),
        ),
    ]
