# Generated by Django 2.0.4 on 2018-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180612_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
