# Generated by Django 2.0.4 on 2018-06-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180612_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Association')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
    ]
