# Generated by Django 2.0.4 on 2018-06-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_associationstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='foo@bar.baz', max_length=254, null=True),
        ),
    ]
